#
# Makefile for usbpd devices
#

obj-$(CONFIG_CCIC_S2MU004)	+= s2mu004-usbpd.o
//obj-$(CONFIG_USE_CCIC)		+= usbpd.o
//obj-$(CONFIG_USE_CCIC)		+= usbpd_policy.o usbpd_manager.o pdic_notifier.o
obj-$(CONFIG_CCIC_NOTIFIER)		+= ccic_notifier.o ccic_sysfs.o
obj-$(CONFIG_CCIC_SM5713)		+= sm5713-usbpd.o
obj-$(CONFIG_CCIC_SM5713)		+= usbpd_sm5713.o usbpd_policy_sm5713.o usbpd_manager_sm5713.o
