#
# Makefile for ccic devices
#


#obj-$(CONFIG_CCIC_NOTIFIER)		+= ccic_notifier.o ccic_sysfs.o ccic_alternate.o
#obj-$(CONFIG_CCIC_S2MM003)		+= s2mm003.o
#obj-$(CONFIG_CCIC_S2MM005)		+= s2mm005_fw.o s2mm005_cc.o s2mm005_pd.o s2mm005.o

obj-$(CONFIG_CCIC_NOTIFIER)		+= ccic_notifier.o ccic_sysfs_sm.o ccic_alternate_sm.o
obj-$(CONFIG_CCIC_SM5507)		+= sm5507_fw.o sm5507_cc.o sm5507_pd.o sm5507.o